IoTHubMonitoring/Models/Average.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text;

namespace IoTHubMonitoring.Models
{
    public class Average
    {
        [Key]
        public long Id { get; set; }
        public string DeviceId { get; set; }
        public DateTimeOffset Timestamp { get; set; }
        public decimal Value { get; set; }
    }   
}

IoTHubMonitoring/Models/DeviceCurrentValueDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IoTHubMonitoring.Models
{
    public class DeviceCurrentValueDto
    {
        public string DeviceId { get; set; }
        public decimal CurrentValue { get; set; }
        public bool? Alarm { get; set; }
        public DateTimeOffset Timestamp { get; set; }
    }
}

IoTHubMonitoring/Models/DeviceDetailsDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IoTHubMonitoring.Models
{
    public class DeviceDetailsDto
    {
        public string DeviceId { get; set; }
        public decimal? SetPoint { get; set; }
        public decimal? AlarmPoint { get; set; }
    }
}

IoTHubMonitoring/Models/DeviceListDto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IoTHubMonitoring.Models
{
    public class DeviceListDto
    {
        public string DeviceId { get; set; }
    }
}

IoTHubMonitoring/Models/ErrorViewModel.cs
using System;

namespace IoTHubMonitoring.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IoTHubMonitoring/Models/IoTDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Text;

namespace IoTHubMonitoring.Models
{
    public class IoTDbContext: DbContext
    {
        private string _connectionString;

        public IoTDbContext(string connectionString)
        {
            _connectionString = connectionString;
        }

        public DbSet<Average> Averages { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer(_connectionString);
        }
    }
}

IoTHubMonitoring/Models/SetAlarmPointRequest.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IoTHubMonitoring.Models
{
    public class SetAlarmPointRequest
    {
        [JsonProperty("alarmPoint")]
        public decimal AlarmPoint { get; set; }
    }
}

IoTHubMonitoring/Models/SetSetPointRequest.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IoTHubMonitoring.Models
{
    public class SetSetPointRequest
    {
        [JsonProperty("setPoint")]
        public decimal SetPoint { get; set; }
    }
}

IoTHubMonitoring/Controllers/DevicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using IoTHubMonitoring.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Devices;
using Microsoft.Extensions.Configuration;
using Microsoft.WindowsAzure.Storage;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace IoTHubMonitoring.Controllers
{
    public class DevicesController : Controller
    {
        private IConfiguration _configuration;

        public DevicesController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            var rm = RegistryManager.CreateFromConnectionString(_configuration["IoTHubConnectionString"]);

            var devicesQuery = rm.CreateQuery("SELECT DeviceId FROM devices");
            var devices = await devicesQuery.GetNextAsJsonAsync();

            var list = new List<DeviceListDto>();

            foreach (var device in devices)
            {
                var json = JsonConvert.DeserializeObject<JObject>(device);
                var dto = new DeviceListDto
                {
                    DeviceId = json.Value<string>("DeviceId")
                };
                list.Add(dto);
            }

            return View(list);
        }

        public async Task<IActionResult> Details(string id)
        {
            var dto = new DeviceDetailsDto();
            dto.DeviceId = id;

            var rm = 
                RegistryManager
                .CreateFromConnectionString(
                    _configuration["IoTHubConnectionString"]);
            var twin = await rm.GetTwinAsync(id);
            if (twin.Properties.Desired.Contains("SetPoint"))
            {
                dto.SetPoint = (decimal)(float)twin.Properties.Desired["SetPoint"];
            }
            if (twin.Properties.Desired.Contains("AlarmPoint"))
            {
                dto.AlarmPoint = (decimal)(float)twin.Properties.Desired["AlarmPoint"];
            }
            return View(dto);
        }

        public async Task<JsonResult> CurrentValue(string id)
        {
            var dto = new DeviceCurrentValueDto();
            dto.DeviceId = id; 

            var storageAccount = CloudStorageAccount
                .Parse(_configuration["StorageConnectionString"]);

            var blobClient = storageAccount.CreateCloudBlobClient();

            var averagesContainer = blobClient.GetContainerReference("averages");

            var blob = averagesContainer.GetBlockBlobReference($"{id}.json");

            var json = await blob.DownloadTextAsync();

            var current = JsonConvert.DeserializeObject<JObject>(json);

            dto.CurrentValue = current.Value<decimal>("Average");
            dto.Timestamp = current.Value<DateTime>("Timestamp");

            var rm = RegistryManager.CreateFromConnectionString(_configuration["IoTHubConnectionString"]);
            var twin = await rm.GetTwinAsync(id);
            if (twin.Properties.Reported.Contains("Alarm"))
            {
                dto.Alarm = (bool)twin.Properties.Reported["Alarm"];
            }
            return Json(dto);
        }


        public async Task<JsonResult> LastTenAverages(string id)
        {
            var dbContext = new IoTDbContext(_configuration["SqlConnectionString"]);
            var query = 
                dbContext
                .Averages
                .Where(xx => xx.DeviceId == id)
                .OrderByDescending(xx => xx.Timestamp)
                .Take(10)
                .Select(xx => new {
                    xx.Timestamp,
                    xx.Value
                })
                ;

            var dto = query.ToList();
            return Json(dto);
        }

        public async Task<IActionResult> SetSetPoint(string id, [FromBody] SetSetPointRequest request)
        {
            var rm = 
                RegistryManager
                .CreateFromConnectionString(
                    _configuration["IoTHubConnectionString"]);
            var twin = await rm.GetTwinAsync(id);
            twin.Properties.Desired["SetPoint"] = request.SetPoint;
            await rm.UpdateTwinAsync(id, twin, twin.ETag);
            return Json(new { Success = true });
        }

        public async Task<IActionResult> SetAlarmPoint(string id, [FromBody] SetAlarmPointRequest request)
        {
            var rm =
                RegistryManager
                .CreateFromConnectionString(
                    _configuration["IoTHubConnectionString"]);
            var twin = await rm.GetTwinAsync(id);
            twin.Properties.Desired["AlarmPoint"] = request.AlarmPoint;
            await rm.UpdateTwinAsync(id, twin, twin.ETag);
            return Json(new { Success = true });
        }
    }
}

IoTHubMonitoring/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IoTHubMonitoring.Models;

namespace IoTHubMonitoring.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IoTHubMonitoring/Views/Devices/Details.cshtml
@model IoTHubMonitoring.Models.DeviceDetailsDto

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2> 

<div>
    <h4>DeviceDetailsDto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DeviceId)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Current value
        </dt>
        <dd id="currentvalue">
            @(0)
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Set point
        </dt>
        <dd>
            @Html.EditorFor(model => model.SetPoint)
            <a href="#" id="setsetpoint" class="btn btn-primary">Set Set Point</a>
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Alarm point
        </dt>
        <dd>
            @Html.EditorFor(model => model.AlarmPoint)
            <a href="#" id="setalarmpoint" class="btn btn-primary">Set Alarm Point</a>
        </dd>
    </dl>
    <dl class="dl-horizontal">
        <dt>
            Alarmed
        </dt>
        <dd id="alarm">
        </dd>
    </dl>
</div>
<div>
    <table id="LastTenAverages" class="table table-striped">
        <thead>
            <tr>
                <th class="col-lg-6">Timestamp</th>
                <th class="col-lg-6">Average</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
@section Scripts
{
    <script type="text/javascript">

        $(function () {

            $("#setsetpoint").click(function (e) {

                var setPoint = $("[name='SetPoint']").val();

                var url = '@Url.Action("SetSetPoint", new { id = Model.DeviceId })';

                $.ajax({
                    url: url,
                    type: 'post',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({
                        setPoint: setPoint
                    })
                });

            });

            
            $("#setalarmpoint").click(function (e) {

                var alarmPoint = $("[name='AlarmPoint']").val();

                var url = '@Url.Action("SetAlarmPoint", new { id = Model.DeviceId })';

                $.ajax({
                    url: url,
                    type: 'post',
                    contentType: "application/json; charset=utf-8",
                    dataType: 'json',
                    data: JSON.stringify({
                        alarmPoint: alarmPoint
                    })
                });

            });


            setInterval(() => {

                var currentValueUrl = '@Url.Action("CurrentValue", new { id = Model.DeviceId })';

                $.getJSON(currentValueUrl, function (response) {

                    $("#currentvalue").html(response.currentValue);
                    $("#alarm").html(response.alarm);

                });

            }, 10000);

            setInterval(() => {

                var lastTenAveragesUrl = '@Url.Action("LastTenAverages", new { id = Model.DeviceId })';

                $.getJSON(lastTenAveragesUrl, function (response) {

                    var tbody = $("#LastTenAverages tbody");
                    tbody.empty();

                    $(response).each((i, item) => {

                        var row = "<tr><td>" + item.timestamp + "</td><td>" + item.value + "</td></tr>";
                        tbody.append(row);

                    });


                });

            }, 20000);


        });

    </script>
}

IoTHubMonitoring/Views/Devices/Index.cshtml
@model IEnumerable<IoTHubMonitoring.Models.DeviceListDto>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeviceId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DeviceId)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id=item.DeviceId })
                </td>
            </tr>
        }
    </tbody>
</table>

IoTHubMonitoring/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IoTHubMonitoring/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IoTHubMonitoring/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

IoTHubMonitoring/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IoTHubMonitoring</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">IoTHubMonitoring</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Devices" asp-action="Index">Devices</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - IoTHubMonitoring</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>